Repository Gesellenstueck/Compass, pull requests merged in 2020-12, with the labels that each got.

#18 💄 Finalize login page
  client/src/App.js
  client/src/GlobalStyles.js
  client/src/components/Button/Button.js
  client/src/components/Input/Input.js
  client/src/pages/Login.js
Labels: Component, Frontend

#17 💄 Redesign of the Card component
  client/src/components/Card/Card.js
  client/src/pages/Dashboard.js
Labels: Component, Frontend

#20 Add Dashboard and style Card Component
  client/src/GlobalStyles.js
  client/src/assets/icons/Add.svg
  client/src/assets/icons/Chat.svg
  client/src/assets/icons/List.svg
  client/src/assets/icons/Lock.svg
  client/src/assets/icons/Overview.svg
  client/src/assets/icons/Smiley.svg
  client/src/assets/icons/Team.svg
  client/src/components/Card/Card.js
  client/src/pages/Dashboard.js
  client/src/pages/Login.js
Labels: Component, Frontend

#21 💩 Fix grid etc., but refactoring is needed
  client/src/components/Card/Card.js
  client/src/pages/Dashboard.js
Labels: Frontend

#34 ✨ Create example survey page for one question
  client/src/assets/images/monsPink.svg
  client/src/assets/images/monsYellow.svg
  client/src/components/Button/SurveyButton.js
  client/src/pages/Survey.js
Labels: Frontend

#37 ✨ Add Backend for survey
  client/package-lock.json
  client/src/App.js
  client/src/api/survey.js
  client/src/api/users.js
  client/src/components/Button/SurveyButton.js
  client/src/pages/Survey.js
  lib/databaseMethods.js
  package.json
  server.js
Labels: Backend

#50 ✨ Add Routing for variable survey pages with useParams
  client/src/App.js
  client/src/api/results.js
  client/src/api/survey.js
  client/src/pages/Dashboard.js
  client/src/pages/Survey.js
  lib/databaseMethods.js
  server.js
Labels: Backend, enhancement

#60 ✨ Add AuthProvider for user data
  .gitignore
  client/package.json
  client/src/App.js
  client/src/context/actions.js
  client/src/context/context.js
  client/src/context/reducer.js
  client/src/pages/Dashboard.js
  client/src/pages/Login.js
  server.js
Labels: Backend

#59 ✨ Add Overview page for results of survey
  client/package.json
  client/src/App.js
  client/src/api/results.js
  client/src/components/Card/CardResult.js
  client/src/pages/Dashboard.js
  client/src/pages/Overview.js
  client/src/pages/Survey.js
  lib/databaseMethods.js
  server.js
Labels: Backend, Frontend, enhancement

#62 ✨ Add charts to overview page
  client/package.json
  client/src/App.js
  client/src/assets/icons/Back.svg
  client/src/components/Card/CardResult.js
  client/src/pages/Overview.js
  lib/databaseMethods.js
Labels: Backend, Frontend, enhancement

#70 ✨ Add flexible styling for draggable cards
  client/src/assets/icons/Chat.svg
  client/src/assets/icons/love.svg
  client/src/components/Card/DraggableCard.js
  client/src/pages/Whiteboard.js
Labels: Frontend

#72 ✨ Create error page and add to router
  client/src/App.js
  client/src/components/Button/Button.js
  client/src/pages/Error.js
Labels: Frontend

#74 💄 Change favicon
  client/public/favicon.ico
Labels: Frontend

#73 💄 Add some small styling changes
  client/src/components/Card/CardResult.js
  client/src/components/Header/Header.js
  client/src/pages/Dashboard.js
  client/src/pages/Overview.js
  client/src/pages/Whiteboard.js
Labels: Frontend
